version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    command: npx nodemon main.ts
    ports:
      - '3000:3000'
    volumes:
      - .:/app/src
      - /app/src/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=test
    networks:
      - my_network

  db:
    image: mysql:5.7.40
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
